server:
  port: 10010
spring:
  application:
    name: gatewayservice
  cloud:
    nacos:
      server-addr: http://43.142.116.134:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=truth,itcast is awesome;
      default-filters:
        - AddRequestHeader=Truth,Itcast Is Awesome;