server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-miqa83wc.sql.tencentcdb.com:20820/springcloud-user
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ShanYiChun@3452
  cloud:
    nacos:
      discovery:
        cluster-name: XT
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pattern:
#  dateformat: yyyy:MM:dd HH:mm:ss
